name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev ninja-build
          pip install jinja2

    - name: Install Dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
          pip install jinja2
          choco install ninja

    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: cmake -B ${{github.workspace}}/build --preset "gdb-github-actions"

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B ${{github.workspace}}/build --preset "windows-github-actions"

    - name: Build
      run: cmake --build .
      working-directory: ${{github.workspace}}/build
