name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build_linux:
    name: Linux - ${{ matrix.buildPreset }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        buildPreset: [Release, Debug]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev ninja-build -y gcc-13 g++-13
      - name: Configure CMake
        run: cmake --preset GCC
      - name: Build
        run: cmake --build . --preset g++-${{ matrix.buildPreset }}
        working-directory: ${{ github.workspace }}
      - name: Test
        run: ./Test --no-graphics
        working-directory: ${{ github.workspace }}/build/GCC/${{ matrix.buildPreset }}
  build_windows:
    name: Windows - ${{ matrix.buildPreset }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        buildPreset: [release, debug]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          choco install ninja
      - name: Configure CMake
        run: cmake --preset visual-studio-17-2022
      - name: Build
        run: cmake --build . --preset msvc-${{ matrix.buildPreset }}
        working-directory: ${{ github.workspace }}
      - name: Test
        run: ./Test --no-graphics
        working-directory: ${{ github.workspace }}/build/visual-studio-17-2022/${{ matrix.buildPreset }}